name: newforms
region: nyc

services:
  - name: web
    github:
      repo: chrissy-b85/newforms
      branch: main
      deploy_on_push: true
    build_command: mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache && composer install --no-dev --optimize-autoloader && npm ci && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache
    run_command: vendor/bin/heroku-php-apache2 public/
    environment_slug: php
    http_port: 8080
    instance_size_slug: basic-xxs
    envs:
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: APP_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: APP_DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: DB_CONNECTION
        scope: RUN_AND_BUILD_TIME
        value: mysql
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${db.HOSTNAME}
      - key: DB_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${db.PORT}
      - key: DB_DATABASE
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE}
